# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_aboutThis.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_aboutThis_Dialog(object):
    def setupUi(self, aboutThis_Dialog):
        aboutThis_Dialog.setObjectName("aboutThis_Dialog")
        aboutThis_Dialog.resize(493, 197)
        self.horizontalLayout = QtWidgets.QHBoxLayout(aboutThis_Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_image = QtWidgets.QLabel(aboutThis_Dialog)
        self.label_image.setText("")
        self.label_image.setObjectName("label_image")
        self.horizontalLayout.addWidget(self.label_image)
        self.label_description = QtWidgets.QLabel(aboutThis_Dialog)
        self.label_description.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_description.setWordWrap(True)
        self.label_description.setObjectName("label_description")
        self.horizontalLayout.addWidget(self.label_description)

        self.retranslateUi(aboutThis_Dialog)
        QtCore.QMetaObject.connectSlotsByName(aboutThis_Dialog)

    def retranslateUi(self, aboutThis_Dialog):
        _translate = QtCore.QCoreApplication.translate
        aboutThis_Dialog.setWindowTitle(_translate("aboutThis_Dialog", "Dialog"))
        self.label_description.setText(_translate("aboutThis_Dialog", "<html><head/><body><p><span style=\" font-weight:700;\">bSDD SimpleGUI </span>- version 18/08/2022</p><p><span style=\" font-weight:700;\">MIT License</span></p><p>Developed by Renan Rocha Ribeiro, Doctorate student at Doctoral Program in Civil Engineering (<span style=\" font-weight:700;\">PDEC</span>) at <span style=\" font-weight:700;\">University of Minho</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    aboutThis_Dialog = QtWidgets.QDialog()
    ui = Ui_aboutThis_Dialog()
    ui.setupUi(aboutThis_Dialog)
    aboutThis_Dialog.show()
    sys.exit(app.exec_())
